//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointnmentId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string Problem { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
